version: '3.2'
services:
  ansible:
    image: theknightcoder/ansible-networking
    entrypoint: bash
    ports:
      - "2222:22"
    volumes:
      - "./:/ansible"
      
  ara:
    image: theknightcoder/ara
    ports:
      - 9191:9191
    volumes:
      - "./db/ara.sqlite:/db/ara.sqlite"
    environment:
      ARA_DATABASE: "sqlite:////db/ara.sqlite"

#docker-compose run --service-ports -d --rm ara
#docker-compose run --service-ports --rm ansible

#cd /vagrant && docker-compose run --service-ports -d ara && docker-compose run --service-ports --rm ansible

#cd /vagrant && docker-compose run --service-ports --rm ansible