---
- name: Napalm get facts
  hosts: "all"
  gather_facts: false
  connection: local 
  
  vars:
    provider:
      hostname: "{{ ansible_host }}"         
      username: '{{ ansible_user }}'         
      dev_os: 'ios'                          
      password: '{{ ansible_password }}'     
    
  tasks:                                     
    - name: get facts from device
      napalm_get_facts:                      
        provider: "{{ provider }}"
        filter: 'facts'                      
      register: output                      

    - debug:
        var: output.ansible_facts.napalm_facts
    - name: delete file
      local_action: file path=./output/facts.xlsx state=absent
      run_once: true
      
    - name: Output JSON variable as XLSX file
      output_excel: 
        content: "{{ output }}"
        dest: ./output/facts.xlsx
      register: result