---
- name: Napalm get facts
  hosts: "ios-devices"
  gather_facts: false
  connection: local 
  
  vars:
    provider:
      hostname: "{{ ansible_host }}"         
      username: '{{ ansible_user }}'         
      dev_os: 'ios'                          
      password: '{{ ansible_password }}'     
    
  tasks:                                     
    - name: get facts from device            
      napalm_get_facts:                      
        provider: "{{ provider }}"
        filter: 'facts,interfaces'                      
      register: output                      

    - name: print results                  
      debug: msg="{{ output }}"         