---
 
- name: PoE Devices
  hosts: localhost
  connection: local
  gather_facts: False
 
  tasks:
    - name: power inline
      ntc_show_command:
        #connection: offline
        connection: ssh
        template_dir: library/ntc_templates
        #file: show_template/test.txt
        platform: cisco_ios 
        command: 'show power inline'
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
      register: poeVar
    - debug: var=poeVar.response
    
    
    - name: cdp neighbors
      ntc_show_command:
        connection: ssh
        template_dir: /usr/share/ansible/ntc-ansible/ntc-templates/templates        
        platform: cisco_ios 
        command: "show cdp neighbors" 
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
      register: cdpVar
    - debug: var=cdpVar.response
    
    - name: output excel
      poe_devices:
        poe: "{{ poeVar }}"
        cdp: "{{ cdpVar }}"
        hostname: "{{ inventory_hostname }}"
        dest: "output/poe.xlsx"