---

- name: Napalm get facts
  hosts: all
  gather_facts: false
  connection: local 
  roles: 
    - ios/connect 
  
    
  tasks:      
    - name: get facts from device
      napalm_get_facts:                      
        provider: "{{ provider }}"
        filter: 'facts' #Other fact filters can be found here https://napalm.readthedocs.io/en/latest/base.html               
      register: output                      

    - name: output to screen
      debug:
        var: output.ansible_facts.napalm_facts
   
    - name: Get Date@Time and set in a variable
      shell: 'date +%Y-%m-%d@%H%M%S'
      register: timestamp
      run_once: true

    - name: Export as Excel file
      export_facts: 
        content: "{{ output }}"
        dest: "./files/{{ timestamp.stdout }}_facts.xlsx"