---
- name: Check if required variables are defined
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: 
    - config_path 
    - ios_provider

- name: Validate
  napalm_install_config:
    provider: "{{ ios_provider }}"
    config_file: "{{ config_path }}"
    commit_changes: false    #true = apply change
    replace_config: "{{ isReplace }}"    #true = config replace false = merge/add to current config
    get_diffs: true
  register: diff                       #Ansible function for collecting output
  failed_when: diff.changed == true
