---
- name: Replace Config
  hosts: all
  gather_facts: false
  connection: local 

  vars_prompt:
    - name: "template path"
      prompt: "Please enter config template path"
      private: no
  
  tasks:
    - include_role: 
        name: ios/replace
      vars:
        template_path: "{{ template }}"
        #var_path: vars.xlsx