---
- name: Apply storm control to all access ports (not trunk)
  hosts: "all"
  gather_facts: false
  connection: local
  
  tasks:                                    
    - name: Get access ports
      ios_command:
        commands: "show interface status"
      register: interfaces_temp
    - set_fact: 
        interfaces: "{{ interfaces_temp.stdout[0] | parse_cli_textfsm('/ansible/lib/parse_cli/cisco_ios_get_access_ports.template') }}"
        
    - include_role: 
        name: ios/merge
      vars:
        template_path: "files/templates/storm_control.j2"
        #var_path: vars.xlsx
